[nc] add tflint
Signed-off-by: Nic Cheneweth <nchenewe@thoughtworks.com>

diff --git a/packages/action.yaml b/packages/action.yaml
--- a/packages/action.yaml
+++ b/packages/action.yaml
@@ -1,3 +1,4 @@
+---
 name: packages
 
 description: Install packages for terraform-action@workflows
@@ -11,6 +12,11 @@ inputs:
 
   terraform-version:
     description: Specify terraform version
+    required: true
+    default: installed
+
+  tflint-version:
+    description: Specify tflint version
     required: true
     default: installed
 
@@ -63,4 +69,40 @@ runs:
           # install and smoke test terraform cli
           sudo unzip -o "terraform_${{ inputs.terraform-version }}_linux_amd64.zip" -d /usr/local/bin
           terraform version
+        fi
+
+    - name: install tflint version ${{ inputs.tflint-version }}
+      working-directory: ${{ inputs.working-directory }}
+      shell: bash
+      run: |
+        if [[ "${{ inputs.tflin-version }}" != "installed" ]]; then
+          # download tflint and verification packages
+          curl -SLO "https://github.com/terraform-linters/tflint/releases/download/v${{ inputs.tflin-version }}/tflint_linux_amd64.zip"
+          curl -SLO "https://github.com/terraform-linters/tflint/releases/download/v${{ inputs.tflin-version }}/checksums.txt"
+          curl -SLO "https://github.com/terraform-linters/tflint/releases/download/v${{ inputs.tflin-version }}/checksums.txt.pem"
+          curl -SLO "https://github.com/terraform-linters/tflint/releases/download/v${{ inputs.tflin-version }}/checksums.txt.keyless.sig"
+
+          # verify cosign origination
+          if result=$(cosign verify-blob --certificate=checksums.txt.pem --signature=checksums.txt.keyless.sig --certificate-identity-regexp="^https://github.com/terraform-linters/tflint" --certificate-oidc-issuer=https://token.actions.githubusercontent.com checksums.txt 2>&1); then
+              echo "Verified cosign build source"
+          else
+              echo "Unable to verify cosign build source"
+              echo "cosign Output:"
+              echo "$result"
+              exit 1
+          fi
+
+          # verify cosign package sha
+          if result=$(shasum --ignore-missing --algorithm 256 --check  checksums.txt 2>&1); then
+              echo "Verified tflint package sha"
+          else
+              echo "Unable to verify tflint package sha"
+              echo "shasum Output:"
+              echo "$result"
+              exit 1
+          fi
+
+          # install and smoke test tflint
+          sudo unzip -o tflint_linux_amd64.zip -d /usr/local/bin
+          tflint --version
         fi
