[nc] add snyk
Signed-off-by: Nic Cheneweth <nchenewe@thoughtworks.com>

diff --git a/packages/action.yaml b/packages/action.yaml
--- a/packages/action.yaml
+++ b/packages/action.yaml
@@ -35,6 +35,11 @@ inputs:
     required: false
     default: installed
 
+  snyk-version:
+    description: Specify snyk version
+    required: false
+    default: installed
+
 runs:
   using: "composite"
   
@@ -243,4 +248,44 @@ runs:
         if [[ "${{ inputs.checkov-version }}" != "installed" ]]; then
           sudo pip install --no-cache-dir checkov==${{ inputs.checkov-version }}
           checkov --version
+        fi
+
+    - name: install snyk version ${{ inputs.snyk-version }}
+      working-directory: ${{ inputs.working-directory }}
+      shell: bash
+      run: |
+        #!/bin/bash
+        if [[ "${{ inputs.snyk-version }}" != "installed" ]]; then
+          # download snyk and verification packages
+          SNYK_SIGNING_KEY=A22665FB96CAB0E0973604C83676C4B8289C296E
+          SNYK_PACKAGE_NAME=$(grep -q 'ID=alpine' /etc/os-release && echo "snyk-alpine" || echo "snyk-linux")
+          curl -sSLO "https://static.snyk.io/cli/v${SNYK_VERSION}/${SNYK_PACKAGE_NAME}"
+          curl -sSLO "https://static.snyk.io/cli/v${SNYK_VERSION}/sha256sums.txt.asc"
+          grep "${SNYK_PACKAGE_NAME}" < sha256sums.txt.asc > checksums.txt
+          gpg --keyserver hkps://keys.openpgp.org --recv-keys "${SNYK_SIGNING_KEY}"
+
+          # verify snyk package sha
+          if result=$(shasum --ignore-missing --algorithm 256 --check  checksums.txt 2>&1); then
+              echo "Verified snyk package sha"
+          else
+              echo "Unable to verify snyk package sha"
+              echo "shasum Output:"
+              echo "$result"
+              exit 1
+          fi
+
+          # verify signature
+          if result=$(gpg --verify sha256sums.txt.asc  2>&1); then
+              echo "Verified signature"
+          else
+              echo "Unable to verify signature"
+              echo "GPG Output:"
+              echo "$result"
+              exit 1
+          fi
+
+          # install and smoke test snyk
+          sudo chmod +x "${SNYK_PACKAGE_NAME}"
+          sudo mv "${SNYK_PACKAGE_NAME}" /usr/local/bin/snyk
+          snyk version
         fi
