[nc] add infracost
Signed-off-by: Nic Cheneweth <nchenewe@thoughtworks.com>

diff --git a/packages/action.yaml b/packages/action.yaml
--- a/packages/action.yaml
+++ b/packages/action.yaml
@@ -54,6 +54,11 @@ inputs:
     required: false
     default: ""
 
+  infracost-version:
+    description: Specify infracost version or "installed" to perform scan. Leave blank to skip.
+    required: false
+    default: ""
+
 runs:
   using: "composite"
   
@@ -375,5 +380,31 @@ runs:
           sudo chmod +x driftctl_linux_amd64
           sudo mv driftctl_linux_amd64 /usr/local/bin/driftctl
           driftctl version
+        fi
 
+    - name: install infracost
+      working-directory: ${{ inputs.working-directory }}
+      shell: bash
+      run: |
+        #!/usr/bin/env bash
+        if [[ "${{ inputs.infracost-version }}" != "installed" && "${{ inputs.infracost-version }}" != "" ]]; then
+          echo "Install infracost v${{ inputs.infracost-version }}"
+          # download infracost and verification packages
+          curl -SLO "https://github.com/infracost/infracost/releases/download/v${INFRACOST_VERSION}/infracost-linux-amd64.tar.gz"
+          curl -SLO "https://github.com/infracost/infracost/releases/download/v${INFRACOST_VERSION}/infracost-linux-amd64.tar.gz.sha256"
+
+          # verify package sha
+          if result=$(shasum --ignore-missing --algorithm 256 --check infracost-linux-amd64.tar.gz.sha256 2>&1); then
+              echo "Verified infracost package sha"
+          else
+              echo "Unable to verify infracost package sha"
+              echo "shasum Output:"
+              echo "$result"
+              exit 1
+          fi
+
+          # install and smoke test infracost
+          sudo tar -xf infracost-linux-amd64.tar.gz
+          sudo mv infracost-linux-amd64 /usr/local/bin/infracost
+          infracost --version
         fi
